# Generated by Django 5.2.6 on 2025-10-07 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='motivo',
            field=models.CharField(default='Sin motivo registrado', max_length=200),
        ),
    ]
