# Generated by Django 5.2.6 on 2025-10-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascotas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('especie', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
