# Generated by Django 5.2.6 on 2025-10-06 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0002_mascotas_delete_producto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mascotas',
            new_name='Mascota',
        ),
    ]
